export interface LoginModel {
  sign: null;
  code: null;
  companyId: string;
  userCode: null;
  isExecutive: number;
  companyAbbreviate: string;
  userName: string;
  companyName: string;
  appMode: string;
  partnerCode: string;
  accessToken: string;
  refreshToken: string;
  type: number;
  businessType: number;
  isH5Back: number;
  isH5Close: number;
  userId: string;
  hrCompanyIds: string;
  accountKeyId: null;
  applyId: null;
  expend: null;
  expendStr: null;
  pufaBankFlag: boolean;
  companyFlag: null;
  oldH5CompanyIds: null;
  spdcreditCardFlag: null;
}